# Generated by Django 4.1.5 on 2023-01-24 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('agent', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('agent_rating', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Leg',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('stops', models.IntegerField(default=0)),
                ('duration_mins', models.IntegerField(default=0)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.airline')),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_airport', to='flights.airport')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_airport', to='flights.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Itinerarie',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('price', models.CharField(blank=True, max_length=255, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.agent')),
                ('legs', models.ManyToManyField(to='flights.leg')),
            ],
        ),
    ]
