# Generated by Django 4.1.5 on 2023-01-24 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('agent', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('agent_rating', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leg',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('departure_airport', models.CharField(blank=True, max_length=255, null=True)),
                ('arrival_airport', models.CharField(blank=True, max_length=255, null=True)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('stops', models.IntegerField(default=0)),
                ('airline_name', models.CharField(blank=True, max_length=255, null=True)),
                ('airline_id', models.CharField(blank=True, max_length=255, null=True)),
                ('duration_mins', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Itinerarie',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('price', models.CharField(blank=True, max_length=255, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.agent')),
                ('legs', models.ManyToManyField(to='flights.leg')),
            ],
        ),
    ]
