# Generated by Django 4.0.5 on 2022-06-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerarie',
            name='legs',
        ),
        migrations.AddField(
            model_name='itinerarie',
            name='legs',
            field=models.ManyToManyField(to='flights.leg'),
        ),
    ]
